eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8769/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
  zipbin:
    base-url: http://localhost:9411
feign:
  hystrix:
    enabled: true

#hystrix-dashboard监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
